service:
  name: notification-service
  version: "1.0.0"

consumers:
  grpc:
    enabled: true
    host: 0.0.0.0
    port: 50052

  rabbitmq:
    enabled: false
    host: rabbit
    port: 5672
    username: guest
    password: guest
    queue_name: notifications


providers:

  sms:
    # Choose from:
    #   - kavenegar
    #   - ghasedak
    #   - twilio
    enabled: true

    kavenegar:
      enabled: true
      api_key: ${KAVEHNEGAR_API_KEY}
      sender: ${KAVEHNEGAR_SENDER}
      timeout: 10

    ghasedak:
      enabled: false
      api_key: ""
      line_number: ""

    twilio:
      enabled: false
      account_sid: ""
      auth_token: ""
      from_number: ""


  email:
    # Choose from:
    #   - smtp
    #   - sendgrid
    enabled: true

    smtp:
      enabled: true
      host: smtp.example.com
      port: 587
      username: ${SMTP_USERNAME}
      password: ${SMTP_PASSWORD}
      use_tls: true
      timeout: 10
      from: no-reply@example.com

    sendgrid:
      enabled: false
      api_key: ""

logging:
  level: INFO
